### ISSUE TITLE
Issue #2: AttackList Function Update

### ISSUE THREAD

**Issue by Alex-Hum** [Alex-Hum/COMP129-Custom-Chess-Resurrection#2]
Issue #2: [AttackList Function Update](https://github.com/Alex-Hum/COMP129-Custom-Chess-Resurrection/blob/39cbd323e21916aeef63239c7ab40d7fed8ca35f/group-project/src/starter/Board.java#L225)

Here, the function to update the attack list for the corresponding chess pieces is basically just duplicate code that's been copy pasted to use different variable names. I feel like there's a way to clean this up so that we can remove the code duplication and simplify the code and make things more visible. I think honestly this could just be a matter of creating a new variable that is assigned the corresponding attack list based off of the chess piece color, make changes to that variable, and then overriding the original attack list with the new variable to save the changes. There are also comments left from our previous time on the project that suggest possibly optimizing the code for the King chess piece case which I think would be good to look into.

**Comment by onzfonz** [comment]
I'd like you to work on this list, but really what I would want you to do that would really help is to have a way to separate out the attack list as data that could then be loaded in, so you could have new custom chess pieces that have an attack list that can be read in from a file
I know that sounds like a lot, but it can still be relatively simple and be a file like

Vertical 1
Horizontal 1
Diagonal 5

And then the piece would be allowed to do those moves
It doesn't completely have to fall in line with chess, but could help make it so that you could more easily create chess variants in the future.

Let me know if you have any questions, but do this one!
